extends Node
signal ammo_changed(new_type)
signal monster_state_changed(new_state)
signal minion_destroyed()
signal monster_collapsed()
signal player_position_updated(position: Vector3)
signal monster_health_changed(current_health: float, max_health: float)
signal monster_defeated()
signal player_damage_requested(amount: float, source_position: Vector3, impulse: Vector3)
signal player_health_changed(current_health: float, max_health: float)
signal player_ammo_changed(in_magazine: int, reserve: int)
signal player_defeated()
signal attack_telegraphed(attack_name: StringName, world_position: Vector3, duration: float)
signal attack_phase_changed(attack_name: StringName, phase_name: StringName, duration: float)
signal monster_anchor_hit(anchor_id: StringName, damage: float, damage_type: int)
signal monster_eye_hit(damage: float, damage_type: int)
signal monster_mouth_hit(damage: float, damage_type: int)
signal monster_mouth_exposure_changed(open: bool, element_type: int)
signal monster_anchor_state_changed(anchor_id: StringName, element_type: int, current_health: float, max_health: float, broken: bool)
signal monster_exposure_changed(exposed: bool, duration: float, damage_remaining: float)
signal monster_combat_message(message: String, positive: bool)
signal weapon_element_changed(element_type: int)
signal eye_swarm_member_updated(member_id: int, position: Vector3, velocity: Vector3)
signal eye_swarm_member_removed(member_id: int)
