extends Node
signal ammo_changed(new_type)
signal monster_state_changed(new_state)
signal minion_destroyed()
signal monster_collapsed()
signal player_position_updated(position: Vector3)
signal monster_health_changed(current_health: float, max_health: float)
signal monster_defeated()
signal player_damage_requested(amount: float, source_position: Vector3, impulse: Vector3)
signal player_health_changed(current_health: float, max_health: float)
signal player_defeated()
signal attack_telegraphed(attack_name: StringName, world_position: Vector3, duration: float)
